version: "3"

services:

  mediabalancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - redis
    links:
      - redis:database

  redis:
    image: redis:latest
    ports:
      - 6379:6379